# Development environment - mount the src folder so that changes are instantly reflected
FROM node:22-alpine AS development
WORKDIR /home/um/react_main

EXPOSE 80
EXPOSE 3001
CMD ["npm", "start"]

# Stage 1: Build the React app
FROM node:22-alpine AS build
WORKDIR /home/um/react_main

# Leverage caching by installing dependencies first
COPY package.json package-lock.json ./
RUN npm install --frozen-lockfile

# Copy the rest of the application code and build for production
COPY . ./
RUN npm run build

# Stage 2: Production environment
FROM nginx:1.29-alpine AS production

# Copy the production build artifacts from the build stage
COPY --from=build /home/um/react_main/build /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# Expose the default NGINX port
EXPOSE 80
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]