FROM node:14.15.1-alpine3.12 as build

WORKDIR /home/um/react_main

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /home/um/react_main/build_public /usr/share/nginx/html
RUN ls -al -R
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]