FROM node:14.15.1-alpine3.12 as build

WORKDIR /home/um/react_main

COPY package*.json ./

RUN npm install

COPY . .

#RUN npm run build

#COPY /home/um/react_main/build /home/um/react_main/build_public

EXPOSE 80
EXPOSE 3001

CMD ["npm", "start"]

#FROM nginx:stable-alpine
#COPY --from=build /home/um/react_main/build /usr/share/nginx/html
#RUN mkdir /etc/nginx/sites-enabled
#COPY --from=build /home/um/react_main/default /etc/nginx/sites-enabled/default
#EXPOSE 80
#CMD ["nginx", "-g", "daemon off;"]