const MEETING_PRIORITY_LOCK = 20;
const MEETING_PRIORITY_JAIL = 10;
const MEETING_PRIORITY_SEANCE = 8;
const MEETING_PRIORITY_BLOB = 7;
const MEETING_PRIORITY_BANQUET = 5;
const MEETING_DEAD_PARTY = 2;
const MEETING_PRIORITY_MATRON = 1;
const MEETING_PRIORITY_DAY = 1;
const MEETING_PRIORITY_SOCIAL = 1;
const MEETING_PRIORITY_HOT_SPRINGS = 1;
const MEETING_PRIORITY_FAKE_CULT = 1;

module.exports = {
  MEETING_PRIORITY_LOCK,
  MEETING_PRIORITY_JAIL,
  MEETING_PRIORITY_SEANCE,
  MEETING_PRIORITY_BLOB,
  MEETING_PRIORITY_BANQUET,
  MEETING_DEAD_PARTY,
  MEETING_PRIORITY_MATRON,
  MEETING_PRIORITY_DAY,
  MEETING_PRIORITY_SOCIAL,
  MEETING_PRIORITY_HOT_SPRINGS,
  MEETING_PRIORITY_FAKE_CULT,
};
