// PRIORITY IS RESOLVED FROM LOWEST NUMBER (-200) TO HIGHEST NUMBER (100)

// WINCHECK PRIORITY
const PRIORITY_WIN_IF_CONDEMNED = -10;
const PRIORITY_WIN_BY_CONDEMNING = -10;
const PRIORITY_WIN_BY_GETTING_SHOT = -10;
const PRIORITY_WIN_CHECK_DEFAULT = 0;
const PRIORITY_WIN_SWAP = 20;

// NIGHT PRIORITY
const PRIORITY_IDENTITY_STEALER_BLOCK = -400;
const PRIORITY_FULL_DISABLE = -400;

const PRIORITY_MODIFY_ACTION_LABELS = -390;
const PRIORITY_UNTARGETABLE = -380;

const PRIORITY_BLOCK_EARLY = -360;
const PRIORITY_SELF_BLOCK_EARLY = -350;

const PRIORITY_ROOM_SWAP = -315;

const PRIORITY_REDIRECT_ACTION = -310;
const PRIORITY_COPY_ACTIONS = -305;
const PRIORITY_SWAP_VISITORS = -304;

const PRIORITY_SELF_BLOCK_LATER = -275;

const PRIORITY_CANCEL_ROLEBLOCK_ACTIONS = -250;
const PRIORITY_BLOCK_VISITORS = -198;
const PRIORITY_NIGHT_ROLE_BLOCKER = -197;

const PRIORITY_MODIFY_ACTION_DELAY = -174;
const PRIORITY_MODIFY_ACTION = -174;

const PRIORITY_SELF_BLOCK_POST_BLOCK = -150;

const PRIORITY_CLEANSE_LYCAN_VISITORS = -92;
const PRIORITY_KILL_WEREWOLF_VISITORS_ENQUEUE = -92;
const PRIORITY_VISITORS_ENQUEUE = -92;

const PRIORITY_NIGHT_SAVER = -90;

const PRIORITY_MODIFY_INVESTIGATIVE_RESULT_DEFAULT = -80;

const PRIORITY_BITING_WOLF = -50;

const PRIORITY_ITEM_GIVER_DEFAULT = -70;
const PRIORITY_EFFECT_GIVER_DEFAULT = -70;
const PRIORITY_ITEM_TAKER_DEFAULT = -65;
const PRIORITY_EFFECT_REMOVER_DEFAULT = -65;

const PRIORITY_REVEAL_DEFAULT = -35;

const PRIORITY_IDENTITY_STEALER = -15;
const PRIORITY_CLEAN_DEATH = -14;

const PRIORITY_KILL_GUESS_ROLE = -5;
const PRIORITY_KILL_SIREN = -4;
const PRIORITY_KILL_SPECIAL = -3;
const PRIORITY_MAFIA_KILL = -1;
const PRIORITY_KILL_DEFAULT = 0;

const PRIORITY_NIGHT_REVIVER = 10;

const PRIORITY_SUPPORT_VISIT_DEFAULT = 30;
const PRIORITY_INVESTIGATIVE_DEFAULT = 50;

const PRIORITY_MIMIC_ROLE = 100;
const PRIORITY_SWAP_ROLES = 130;
const PRIORITY_CONVERT_DEFAULT = 150;


const PRIORITY_BECOME_DEAD_ROLE = 170;

const PRIORITY_INVESTIGATIVE_AFTER_RESOLVE_DEFAULT = 250;

// DAY PRIORITY
const PRIORITY_OVERTHROW_VOTE = -20;
const PRIORITY_SUNSET_DEFAULT = -10;
const PRIORITY_DAY_EFFECT_DEFAULT = -2;
const PRIORITY_VILLAGE_MEETING = 0;
const PRIORITY_DAY_DEFAULT = 0;

// LEADER PRIORITY
const PRIORITY_LEADER_DEFAULT = 2;
const PRIORITY_LEADER_NINJA = 3;

module.exports = {
  // WINCHECK PRIORITY
  PRIORITY_WIN_CHECK_DEFAULT,
  PRIORITY_WIN_IF_CONDEMNED,
  PRIORITY_WIN_BY_CONDEMNING,
  PRIORITY_WIN_BY_GETTING_SHOT,
  PRIORITY_WIN_SWAP,

  // NIGHT PRIORITY
  PRIORITY_IDENTITY_STEALER_BLOCK,
  PRIORITY_FULL_DISABLE,

  PRIORITY_UNTARGETABLE,
  PRIORITY_MODIFY_ACTION_LABELS,
  PRIORITY_MODIFY_ACTION_DELAY,
  PRIORITY_MODIFY_ACTION,
  PRIORITY_ROOM_SWAP,

  PRIORITY_BLOCK_EARLY,

  PRIORITY_REDIRECT_ACTION,
  PRIORITY_COPY_ACTIONS,
  PRIORITY_SWAP_VISITORS,

  PRIORITY_CANCEL_ROLEBLOCK_ACTIONS,
  PRIORITY_BLOCK_VISITORS,
  PRIORITY_NIGHT_ROLE_BLOCKER,

  PRIORITY_CLEANSE_LYCAN_VISITORS,
  PRIORITY_KILL_WEREWOLF_VISITORS_ENQUEUE,
  PRIORITY_VISITORS_ENQUEUE,
  PRIORITY_NIGHT_SAVER,

  PRIORITY_BITING_WOLF,

  PRIORITY_MODIFY_INVESTIGATIVE_RESULT_DEFAULT,

  PRIORITY_ITEM_GIVER_DEFAULT,
  PRIORITY_EFFECT_GIVER_DEFAULT,
  PRIORITY_ITEM_TAKER_DEFAULT,
  PRIORITY_EFFECT_REMOVER_DEFAULT,

  PRIORITY_SUPPORT_VISIT_DEFAULT,
  PRIORITY_INVESTIGATIVE_DEFAULT,
  PRIORITY_REVEAL_DEFAULT,

  PRIORITY_MIMIC_ROLE,
  PRIORITY_SWAP_ROLES,
  PRIORITY_CONVERT_DEFAULT,

  PRIORITY_CLEAN_DEATH,
  PRIORITY_IDENTITY_STEALER,

  PRIORITY_MAFIA_KILL,

  PRIORITY_KILL_GUESS_ROLE,
  PRIORITY_KILL_SPECIAL,
  PRIORITY_KILL_SIREN,
  PRIORITY_KILL_DEFAULT,

  PRIORITY_NIGHT_REVIVER,

  PRIORITY_BECOME_DEAD_ROLE,

  PRIORITY_INVESTIGATIVE_AFTER_RESOLVE_DEFAULT,

  // DAY PRIORITY
  PRIORITY_OVERTHROW_VOTE,
  PRIORITY_SUNSET_DEFAULT,
  PRIORITY_VILLAGE_MEETING,
  PRIORITY_DAY_DEFAULT,

  // LEADER PRIORITY
  PRIORITY_LEADER_DEFAULT,
  PRIORITY_LEADER_NINJA,
};
