// PRIORITY IS RESOLVED FROM LOWEST NUMBER (-101) TO HIGHEST NUMBER (100)

// WINCHECK PRIORITY
const PRIORITY_WIN_CHECK_DEFAULT = 0;

// NIGHT PRIORITY

const PRIORITY_INSANITY = -80;

const PRIORITY_NIGHT_SAVER = -60;
const PRIORITY_NIGHT_ROLE_BLOCKER = -60;

const PRIORITY_LEADER = -40;

const PRIORITY_FOLLOWER = -20;

const PRIORITY_KILL_DEFAULT = 0;
const PRIORITY_NIGHT_REVIVER = 0;

const PRIORITY_INVESTIGATIVE_DEFAULT = 20;


// DAY PRIORITY
const PRIORITY_SUNSET_DEFAULT = -10;
const PRIORITY_VILLAGE_MEETING = 0;
const PRIORITY_DAY_DEFAULT = 0;

module.exports = {
  // WINCHECK PRIORITY
  PRIORITY_WIN_CHECK_DEFAULT,

  // NIGHT PRIORITY

  PRIORITY_INSANITY,

  PRIORITY_NIGHT_SAVER,
  PRIORITY_NIGHT_ROLE_BLOCKER,
  
  PRIORITY_LEADER,
  
  PRIORITY_FOLLOWER,
  
  PRIORITY_KILL_DEFAULT,
  
  PRIORITY_NIGHT_REVIVER,
  
  PRIORITY_INVESTIGATIVE_DEFAULT,

  // DAY PRIORITY
  PRIORITY_SUNSET_DEFAULT,
  PRIORITY_VILLAGE_MEETING,
  PRIORITY_DAY_DEFAULT,
};
