// PRIORITY IS RESOLVED FROM LOWEST NUMBER (-101) TO HIGHEST NUMBER (100)

// WINCHECK PRIORITY
const PRIORITY_WIN_CHECK_DEFAULT = 0;

// NIGHT PRIORITY

const PRIORITY_UNTARGETABLE = -180;
const PRIORITY_MODIFY_ACTION_LABELS = -120;

const PRIORITY_BLOCK_VISITORS = -96;
const PRIORITY_NIGHT_ROLE_BLOCKER = -95;

const PRIORITY_VISITORS_ENQUEUE = -92;

const PRIORITY_NIGHT_SAVER = -90;

const PRIORITY_MESSAGE_GIVER_DEFAULT = -55;
const PRIORITY_CONFIRM_SELF = PRIORITY_MESSAGE_GIVER_DEFAULT;

const PRIORITY_MODIFY_INVESTIGATIVE_RESULT_DEFAULT = -50;
const PRIORITY_REVEAL_TARGET_ON_DEATH =
  PRIORITY_MODIFY_INVESTIGATIVE_RESULT_DEFAULT;
const PRIORITY_MODIFY_ALIGNMENT = PRIORITY_MODIFY_INVESTIGATIVE_RESULT_DEFAULT;

const PRIORITY_ITEM_GIVER_DEFAULT = -50;
const PRIORITY_EFFECT_GIVER_DEFAULT = -50;
const PRIORITY_ITEM_TAKER_DEFAULT = -45;
const PRIORITY_EFFECT_REMOVER_DEFAULT = -45;

const PRIORITY_INVESTIGATIVE_DEFAULT = -10;

const PRIORITY_SWAP_ROLES = -4;
const PRIORITY_CONVERT_DEFAULT = -3;

const PRIORITY_IDENTITY_STEALER = -2;

const PRIORITY_CULT_CONVERT = -2;
const PRIORITY_MAFIA_KILL = -1;

const PRIORITY_KILL_DEFAULT = 0;

const PRIORITY_NIGHT_REVIVER = 1;

const PRIORITY_BECOME_DEAD_ROLE = 50;

const PRIORITY_INVESTIGATIVE_AFTER_RESOLVE_DEFAULT = 100;

// DAY PRIORITY
const PRIORITY_SUNSET_DEFAULT = -10;
const PRIORITY_VILLAGE_MEETING = 0;
const PRIORITY_DAY_DEFAULT = 0;

// LEADER PRIORITY
const PRIORITY_LEADER_DEFAULT = 1;

module.exports = {
  // WINCHECK PRIORITY
  PRIORITY_WIN_CHECK_DEFAULT,

  // NIGHT PRIORITY

  PRIORITY_UNTARGETABLE,
  PRIORITY_MODIFY_ACTION_LABELS,

  PRIORITY_NIGHT_ROLE_BLOCKER,
  PRIORITY_BLOCK_VISITORS,
  PRIORITY_VISITORS_ENQUEUE,
  PRIORITY_NIGHT_SAVER,

  PRIORITY_MESSAGE_GIVER_DEFAULT,
  PRIORITY_CONFIRM_SELF,

  PRIORITY_MODIFY_INVESTIGATIVE_RESULT_DEFAULT,
  PRIORITY_REVEAL_TARGET_ON_DEATH,
  PRIORITY_MODIFY_ALIGNMENT,

  PRIORITY_ITEM_GIVER_DEFAULT,
  PRIORITY_EFFECT_GIVER_DEFAULT,
  PRIORITY_ITEM_TAKER_DEFAULT,
  PRIORITY_EFFECT_REMOVER_DEFAULT,

  PRIORITY_INVESTIGATIVE_DEFAULT,

  PRIORITY_SWAP_ROLES,
  PRIORITY_CONVERT_DEFAULT,

  PRIORITY_IDENTITY_STEALER,

  PRIORITY_CULT_CONVERT,
  PRIORITY_MAFIA_KILL,

  PRIORITY_KILL_DEFAULT,

  PRIORITY_NIGHT_REVIVER,

  PRIORITY_BECOME_DEAD_ROLE,

  PRIORITY_INVESTIGATIVE_AFTER_RESOLVE_DEFAULT,

  // DAY PRIORITY
  PRIORITY_SUNSET_DEFAULT,
  PRIORITY_VILLAGE_MEETING,
  PRIORITY_DAY_DEFAULT,

  // LEADER PRIORITY
  PRIORITY_LEADER_DEFAULT,
};
