const Standard_Deck = [
  //Hearts
  "Ace-Hearts",
  "2-Hearts",
  "3-Hearts",
  "4-Hearts",
  "5-Hearts",
  "6-Hearts",
  "7-Hearts",
  "8-Hearts",
  "9-Hearts",
  "10-Hearts",
  "Jack-Hearts",
  "Queen-Hearts",
  "King-Hearts",
  //Diamonds
  "Ace-Diamonds",
  "2-Diamonds",
  "3-Diamonds",
  "4-Diamonds",
  "5-Diamonds",
  "6-Diamonds",
  "7-Diamonds",
  "8-Diamonds",
  "9-Diamonds",
  "10-Diamonds",
  "Jack-Diamonds",
  "Queen-Diamonds",
  "King-Diamonds",
  //Clubs
  "Ace-Clubs",
  "2-Clubs",
  "3-Clubs",
  "4-Clubs",
  "5-Clubs",
  "6-Clubs",
  "7-Clubs",
  "8-Clubs",
  "9-Clubs",
  "10-Clubs",
  "Jack-Clubs",
  "Queen-Clubs",
  "King-Clubs",
  //Spades
  "Ace-Spades",
  "2-Spades",
  "3-Spades",
  "4-Spades",
  "5-Spades",
  "6-Spades",
  "7-Spades",
  "8-Spades",
  "9-Spades",
  "10-Spades",
  "Jack-Spades",
  "Queen-Spades",
  "King-Spades",
];
/*
const Standard_Deck_WIP = [
  //Hearts
  "Ace-Hearts": {
    name: "Ace-Hearts",
    suit: "Hearts",
    rank: [14,1],
    id: 01,
  },
  "2-Hearts": {
    name: "2-Hearts",
    suit: "Hearts",
    rank: [2],
    id: 01,
  },
  "3-Hearts": {
    name: "3-Hearts",
    suit: "Hearts",
    rank: [3],
    id: 01,
  },
  "4-Hearts": {
    name: "4-Hearts",
    suit: "Hearts",
    rank: [4],
    id: 01,
  },
  "5-Hearts": {
    name: "5-Hearts",
    suit: "Hearts",
    rank: [5],
    id: 01,
  },
  "6-Hearts": {
    name: "6-Hearts",
    suit: "Hearts",
    rank: [6],
    id: 01,
  },
  "7-Hearts": {
    name: "7-Hearts",
    suit: "Hearts",
    rank: [7],
    id: 01,
  },
  "8-Hearts": {
    name: "8-Hearts",
    suit: "Hearts",
    rank: [8],
    id: 01,
  },
  "9-Hearts": {
    name: "9-Hearts",
    suit: "Hearts",
    rank: [9],
    id: 01,
  },
  "10-Hearts": {
    name: "10-Hearts",
    suit: "Hearts",
    rank: [10],
    id: 01,
  },
  "Jack-Hearts": {
    name: "Jack-Hearts",
    suit: "Hearts",
    rank: [11],
    id: 01,
  },
  "Queen-Hearts": {
    name: "Queen-Hearts",
    suit: "Hearts",
    rank: [12],
    id: 01,
  },
"King-Hearts": {
    name: "King-Hearts",
    suit: "Hearts",
    rank: [13],
    id: 01,
  },
  //Clubs
  "Ace-Clubs": {
    name: "Ace-Clubs",
    suit: "Clubs",
    rank: [14,1],
    id: 01,
  },
  "2-Clubs": {
    name: "2-Clubs",
    suit: "Clubs",
    rank: [2],
    id: 01,
  },
  "3-Clubs": {
    name: "3-Clubs",
    suit: "Clubs",
    rank: [3],
    id: 01,
  },
  "4-Clubs": {
    name: "4-Clubs",
    suit: "Clubs",
    rank: [4],
    id: 01,
  },
  "5-Clubs": {
    name: "5-Clubs",
    suit: "Clubs",
    rank: [5],
    id: 01,
  },
  "6-Clubs": {
    name: "6-Clubs",
    suit: "Clubs",
    rank: [6],
    id: 01,
  },
  "7-Clubs": {
    name: "7-Clubs",
    suit: "Clubs",
    rank: [7],
    id: 01,
  },
  "8-Clubs": {
    name: "8-Clubs",
    suit: "Clubs",
    rank: [8],
    id: 01,
  },
  "9-Clubs": {
    name: "9-Clubs",
    suit: "Clubs",
    rank: [9],
    id: 01,
  },
  "10-Clubs": {
    name: "10-Clubs",
    suit: "Clubs",
    rank: [10],
    id: 01,
  },
  "Jack-Clubs": {
    name: "Jack-Clubs",
    suit: "Clubs",
    rank: [11],
    id: 01,
  },
  "Queen-Clubs": {
    name: "Queen-Clubs",
    suit: "Clubs",
    rank: [12],
    id: 01,
  },
"King-Clubs": {
    name: "King-Clubs",
    suit: "Clubs",
    rank: [13],
    id: 01,
  },
  //Diamounds
  "Ace-Diamonds": {
    name: "Ace-Diamonds",
    suit: "Diamonds",
    rank: [14,1],
    id: 01,
  },
  "2-Diamonds": {
    name: "2-Diamonds",
    suit: "Diamonds",
    rank: [2],
    id: 01,
  },
  "3-Diamonds": {
    name: "3-Diamonds",
    suit: "Diamonds",
    rank: [3],
    id: 01,
  },
  "4-Diamonds": {
    name: "4-Diamonds",
    suit: "Diamonds",
    rank: [4],
    id: 01,
  },
  "5-Diamonds": {
    name: "5-Diamonds",
    suit: "Diamonds",
    rank: [5],
    id: 01,
  },
  "6-Diamonds": {
    name: "6-Diamonds",
    suit: "Diamonds",
    rank: [6],
    id: 01,
  },
  "7-Diamonds": {
    name: "7-Diamonds",
    suit: "Diamonds",
    rank: [7],
    id: 01,
  },
  "8-Diamonds": {
    name: "8-Diamonds",
    suit: "Diamonds",
    rank: [8],
    id: 01,
  },
  "9-Diamonds": {
    name: "9-Diamonds",
    suit: "Diamonds",
    rank: [9],
    id: 01,
  },
  "10-Diamonds": {
    name: "10-Diamonds",
    suit: "Diamonds",
    rank: [10],
    id: 01,
  },
  "Jack-Diamonds": {
    name: "Jack-Diamonds",
    suit: "Diamonds",
    rank: [11],
    id: 01,
  },
  "Queen-Diamonds": {
    name: "Queen-Diamonds",
    suit: "Diamonds",
    rank: [12],
    id: 01,
  },
"King-Diamonds": {
    name: "King-Diamonds",
    suit: "Diamonds",
    rank: [13],
    id: 01,
  },
  //Spades
  "Ace-Spades": {
    name: "Ace-Spades",
    suit: "Spades",
    rank: [14,1],
    id: 01,
  },
  "2-Spades": {
    name: "2-Spades",
    suit: "Spades",
    rank: [2],
    id: 01,
  },
  "3-Spades": {
    name: "3-Spades",
    suit: "Spades",
    rank: [3],
    id: 01,
  },
  "4-Spades": {
    name: "4-Spades",
    suit: "Spades",
    rank: [4],
    id: 01,
  },
  "5-Spades": {
    name: "5-Spades",
    suit: "Spades",
    rank: [5],
    id: 01,
  },
  "6-Spades": {
    name: "6-Spades",
    suit: "Spades",
    rank: [6],
    id: 01,
  },
  "7-Spades": {
    name: "7-Spades",
    suit: "Spades",
    rank: [7],
    id: 01,
  },
  "8-Spades": {
    name: "8-Spades",
    suit: "Spades",
    rank: [8],
    id: 01,
  },
  "9-Spades": {
    name: "9-Spades",
    suit: "Diamonds",
    rank: [9],
    id: 01,
  },
  "10-Spades": {
    name: "10-Spades",
    suit: "Spades",
    rank: [10],
    id: 01,
  },
  "Jack-Spades": {
    name: "Jack-Spades",
    suit: "Spades",
    rank: [11],
    id: 01,
  },
  "Queen-Spades": {
    name: "Queen-Spades",
    suit: "Spades",
    rank: [12],
    id: 01,
  },
"King-Spades": {
    name: "King-Spades",
    suit: "Spades",
    rank: [13],
    id: 01,
  },
  ];
*/
const Test_Deck = [
  //Hearts
  "Ace-Hearts",
  "Ace-Clubs",
  "Ace-Spades",
  "2-Spades",
  "5-Hearts",
  "5-Clubs",
  "4-Hearts",
  "3-Hearts",
  "2-Hearts",
];

module.exports = {
  Standard_Deck,
  Test_Deck,
};
