const Standard_Deck = [
  //Hearts
  "Ace-Hearts",
  "2-Hearts",
  "3-Hearts",
  "4-Hearts",
  "5-Hearts",
  "6-Hearts",
  "7-Hearts",
  "8-Hearts",
  "9-Hearts",
  "10-Hearts",
  "Jack-Hearts",
  "Queen-Hearts",
  "King-Hearts",
  //Diamonds
  "Ace-Diamonds",
  "2-Diamonds",
  "3-Diamonds",
  "4-Diamonds",
  "5-Diamonds",
  "6-Diamonds",
  "7-Diamonds",
  "8-Diamonds",
  "9-Diamonds",
  "10-Diamonds",
  "Jack-Diamonds",
  "Queen-Diamonds",
  "King-Diamonds",
  //Clubs
  "Ace-Clubs",
  "2-Clubs",
  "3-Clubs",
  "4-Clubs",
  "5-Clubs",
  "6-Clubs",
  "7-Clubs",
  "8-Clubs",
  "9-Clubs",
  "10-Clubs",
  "Jack-Clubs",
  "Queen-Clubs",
  "King-Clubs",
  //Spades
  "Ace-Spades",
  "2-Spades",
  "3-Spades",
  "4-Spades",
  "5-Spades",
  "6-Spades",
  "7-Spades",
  "8-Spades",
  "9-Spades",
  "10-Spades",
  "Jack-Spades",
  "Queen-Spades",
  "King-Spades",
];

const Standard_Deck_WIP = [
  //Hearts
  "Ace-Hearts": {
    name: "Ace-Hearts",
    suit: "Hearts",
    rank: [14,1],
    id: 01,
  },
  "2-Hearts": {
    name: "2-Hearts",
    suit: "Hearts",
    rank: [2],
    id: 01,
  },
  "3-Hearts": {
    name: "3-Hearts",
    suit: "Hearts",
    rank: [3],
    id: 01,
  },
  "4-Hearts": {
    name: "4-Hearts",
    suit: "Hearts",
    rank: [4],
    id: 01,
  },
  "5-Hearts": {
    name: "5-Hearts",
    suit: "Hearts",
    rank: [5],
    id: 01,
  },
  "6-Hearts": {
    name: "6-Hearts",
    suit: "Hearts",
    rank: [6],
    id: 01,
  },
  "7-Hearts": {
    name: "7-Hearts",
    suit: "Hearts",
    rank: [7],
    id: 01,
  },
  "8-Hearts": {
    name: "8-Hearts",
    suit: "Hearts",
    rank: [8],
    id: 01,
  },
  "9-Hearts": {
    name: "9-Hearts",
    suit: "Hearts",
    rank: [9],
    id: 01,
  },
  "10-Hearts": {
    name: "10-Hearts",
    suit: "Hearts",
    rank: [10],
    id: 01,
  },
  "Jack-Hearts": {
    name: "Jack-Hearts",
    suit: "Hearts",
    rank: [11],
    id: 01,
  },
  "Queen-Hearts": {
    name: "Queen-Hearts",
    suit: "Hearts",
    rank: [12],
    id: 01,
  },
"King-Hearts": {
    name: "Queen-Hearts",
    suit: "Hearts",
    rank: [13],
    id: 01,
  },
];

const Test_Deck = [
  //Hearts
  "Ace-Hearts",
  "Ace-Clubs",
  "Ace-Spades",
  "2-Spades",
  "5-Hearts",
  "5-Clubs",
  "4-Hearts",
  "3-Hearts",
  "2-Hearts",
];

module.exports = {
  Standard_Deck,
  Test_Deck,
};
